
export const equations = {
  "basic-algebra": [
    { label: "Addition", value: "a + b" },
    { label: "Subtraction", value: "x - y" },
    { label: "Multiplication", value: "c \\cdot d" },
    { label: "Division", value: "k / m" },
    { label: "Exponent", value: "x^2" },
    { label: "Subscript", value: "a_n" },
    { label: "Fraction", value: "\\frac{a}{b}" },
    { label: "Binomial", value: "\\binom{n}{k}" },
    { label: "Absolute Value", value: "|x|" },
    { label: "Floor", value: "\\lfloor x \\rfloor" },
    { label: "Ceiling", value: "\\lceil y \\rceil" },
  ],
  "roots-radicals": [
    { label: "Square Root", value: "\\sqrt{x}" },
    { label: "N-th Root", value: "\\sqrt[n]{x}" },
  ],
  "relations-operators": [
    { label: "Equals", value: "=" },
    { label: "Not Equal", value: "\\neq" },
    { label: "Approximate", value: "\\approx" },
    { label: "Similar", value: "\\sim" },
    { label: "Equivalent", value: "\\equiv" },
    { label: "Less Than", value: "<" },
    { label: "Greater Than", value: ">" },
    { label: "Less Than or Equal", value: "\\leq" },
    { label: "Greater Than or Equal", value: "\\geq" },
  ],
  calculus: [
    { label: "Limit", value: "\\lim_{x \\to a} f(x)" },
    { label: "Derivative", value: "\\frac{dy}{dx}" },
    { label: "Partial Derivative", value: "\\frac{\\partial f}{\\partial x}" },
    { label: "Integral", value: "\\int_a^b f(x) dx" },
    { label: "Summation", value: "\\sum_{i=1}^n" },
    { label: "Product", value: "\\prod_{j=0}^{\\infty}" },
  ],
  "functions-operators": [
    { label: "Sine", value: "\\sin x" },
    { label: "Cosine", value: "\\cos^2(\\theta)" },
    { label: "Tangent", value: "\\tan^{-1}(x)" },
    { label: "Logarithm", value: "\\log x" },
    { label: "Natural Log", value: "\\ln y" },
    { label: "Exponential", value: "e^x" },
  ],
  "matrices-vectors": [
    { label: "Vector", value: "\\vec{v}" },
    { label: "Matrix", value: "\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}" },
    { label: "Determinant", value: "\\det(A)" },
    { label: "Dot Product", value: "\\vec{a} \\cdot \\vec{b}" },
    { label: "Cross Product", value: "\\vec{a} \\times \\vec{b}" },
    { label: "Norm", value: "\\|x\|" },
  ],
  "accents-decorations": [
    { label: "Hat", value: "\\hat{a}" },
    { label: "Bar", value: "\\bar{x}" },
    { label: "Vector Arrow", value: "\\vec{v}" },
    { label: "Overbrace", value: "\\overbrace{a+b+c}^{n}" },
    { label: "Underbrace", value: "\\underbrace{x+y+z}_{m}" },
  ],
  "delimiters-scaling": [
    { label: "Parentheses", value: "()" },
    { label: "Brackets", value: "[]" },
    { label: "Braces", value: "\\{ \\}" },
    { label: "Angle Brackets", value: "\\langle \\rangle" },
    { label: "Auto-scaling", value: "\\left( \\frac{a}{b} \right)" },
  ],
  "logical-set-notation": [
    { label: "For All", value: "\\forall" },
    { label: "Exists", value: "\\exists" },
    { label: "Logical And", value: "\\land" },
    { label: "Logical Or", value: "\\lor" },
    { label: "Not", value: "\\neg" },
    { label: "Real Numbers", value: "\\mathbb{R}" },
  ],
  "multiline-aligned": [
    { label: "Aligned", value: "\\begin{align} x &= y \\\\ z &= w \\end{align}" },
    { label: "Cases", value: "\\begin{cases} a & \\text{if } b \\\\ c & \\text{if } d \\end{cases}" },
  ],
  "special-characters": [
    { label: "Alpha", value: "\\alpha" },
    { label: "Beta", value: "\\beta" },
    { label: "Gamma", value: "\\gamma" },
    { label: "Pi", value: "\\pi" },
    { label: "Infinity", value: "\\infty" },
    { label: "Empty Set", value: "\\emptyset" },
  ],
  "formatting-text": [
    { label: "Bold", value: "\\mathbf{x}" },
    { label: "Italic", value: "\\mathit{x}" },
    { label: "Text", value: "\\text{for all }" },
    { label: "Space", value: "\\quad" },
  ],
};
