/** Cursor marker `|` is removed on insertion; selected text replaces it. */
export type SymbolItem = { name: string; glyph: string; latex: string; search?: string };
export type SymbolGroup = { name: string; items: SymbolItem[] };
const s = (name: string, glyph: string, latex: string, search = ""): SymbolItem => ({ name, glyph, latex, search });

export const symbolGroups: SymbolGroup[] = [
  { name: "Essentials", items: [
    s("Fraction", "a⁄b", String.raw`\frac{|}{b}`, "divide quotient"),
    s("Square root", "√x", String.raw`\sqrt{|}`),
    s("Power", "xⁿ", "^{|}"), s("Subscript", "xₙ", "_{|}"),
    s("Sum", "∑", String.raw`\sum_{i=1}^{n} |`), s("Integral", "∫", String.raw`\int_{a}^{b} |\,dx`),
    s("Limit", "lim", String.raw`\lim_{x\to 0} |`), s("Infinity", "∞", String.raw`\infty`),
    s("Pi", "π", String.raw`\pi`), s("Theta", "θ", String.raw`\theta`),
    s("Partial", "∂", String.raw`\partial`), s("Plus minus", "±", String.raw`\pm`),
    s("Times", "×", String.raw`\times`), s("Not equal", "≠", String.raw`\neq`),
    s("Less or equal", "≤", String.raw`\leq`), s("Right arrow", "→", String.raw`\rightarrow`),
    s("Vector", "x⃗", String.raw`\vec{|}`), s("Parentheses", "( )", String.raw`\left(|\right)`),
    s("Matrix", "▦", String.raw`\begin{pmatrix}| & b \\ c & d\end{pmatrix}`),
    s("Text", "abc", String.raw`\text{|}`),
  ]},
  { name: "Structures", items: [
    s("Fraction", "a⁄b", String.raw`\frac{|}{b}`), s("Display fraction", "⅔", String.raw`\dfrac{|}{b}`),
    s("Small fraction", "¹⁄₂", String.raw`\tfrac{|}{b}`), s("Binomial", "(ⁿₖ)", String.raw`\binom{|}{k}`),
    s("Square root", "√", String.raw`\sqrt{|}`), s("Nth root", "ⁿ√", String.raw`\sqrt[n]{|}`),
    s("Superscript", "xⁿ", "^{|}"), s("Subscript", "xₙ", "_{|}"),
    s("Both scripts", "xₙᵐ", "_{i}^{|}"), s("Overbrace", "⏞", String.raw`\overbrace{|}^{text}`),
    s("Underbrace", "⏟", String.raw`\underbrace{|}_{text}`), s("Overset", "a⁺", String.raw`\overset{*}{|}`),
    s("Underset", "aₓ", String.raw`\underset{x}{|}`), s("Cases", "{·", String.raw`\begin{cases}| & x>0 \\ 0 & x\leq 0\end{cases}`),
    s("Aligned", "≡", String.raw`\begin{aligned}| &= b \\ c &= d\end{aligned}`),
    s("Equation array", "⋮", String.raw`\begin{array}{cc}| & b \\ c & d\end{array}`),
  ]},
  { name: "Greek", items: [
    s("Alpha", "α", String.raw`\alpha`),s("Beta", "β", String.raw`\beta`),s("Gamma", "γ", String.raw`\gamma`),
    s("Delta", "δ", String.raw`\delta`),s("Epsilon", "ε", String.raw`\epsilon`),s("Variant epsilon", "ϵ", String.raw`\varepsilon`),
    s("Zeta", "ζ", String.raw`\zeta`),s("Eta", "η", String.raw`\eta`),s("Theta", "θ", String.raw`\theta`),s("Variant theta", "ϑ", String.raw`\vartheta`),
    s("Iota", "ι", String.raw`\iota`),s("Kappa", "κ", String.raw`\kappa`),s("Lambda", "λ", String.raw`\lambda`),s("Mu", "μ", String.raw`\mu`),
    s("Nu", "ν", String.raw`\nu`),s("Xi", "ξ", String.raw`\xi`),s("Omicron", "ο", "o"),s("Pi", "π", String.raw`\pi`),
    s("Rho", "ρ", String.raw`\rho`),s("Sigma", "σ", String.raw`\sigma`),s("Final sigma", "ς", String.raw`\varsigma`),
    s("Tau", "τ", String.raw`\tau`),s("Upsilon", "υ", String.raw`\upsilon`),s("Phi", "φ", String.raw`\phi`),
    s("Variant phi", "ϕ", String.raw`\varphi`),s("Chi", "χ", String.raw`\chi`),s("Psi", "ψ", String.raw`\psi`),s("Omega", "ω", String.raw`\omega`),
    s("Gamma uppercase", "Γ", String.raw`\Gamma`),s("Delta uppercase", "Δ", String.raw`\Delta`),s("Theta uppercase", "Θ", String.raw`\Theta`),
    s("Lambda uppercase", "Λ", String.raw`\Lambda`),s("Xi uppercase", "Ξ", String.raw`\Xi`),s("Pi uppercase", "Π", String.raw`\Pi`),
    s("Sigma uppercase", "Σ", String.raw`\Sigma`),s("Upsilon uppercase", "Υ", String.raw`\Upsilon`),s("Phi uppercase", "Φ", String.raw`\Phi`),
    s("Psi uppercase", "Ψ", String.raw`\Psi`),s("Omega uppercase", "Ω", String.raw`\Omega`),
  ]},
  { name: "Operators", items: [
    s("Plus minus", "±", String.raw`\pm`),s("Minus plus", "∓", String.raw`\mp`),s("Times", "×", String.raw`\times`),
    s("Divide", "÷", String.raw`\div`),s("Dot product", "⋅", String.raw`\cdot`),s("Asterisk", "∗", String.raw`\ast`),
    s("Circle", "∘", String.raw`\circ`),s("Bullet", "∙", String.raw`\bullet`),s("Star", "⋆", String.raw`\star`),
    s("Oplus", "⊕", String.raw`\oplus`),s("Ominus", "⊖", String.raw`\ominus`),s("Otimes", "⊗", String.raw`\otimes`),
    s("Oslash", "⊘", String.raw`\oslash`),s("Odot", "⊙", String.raw`\odot`),s("Cap", "∩", String.raw`\cap`),
    s("Cup", "∪", String.raw`\cup`),s("Sqcap", "⊓", String.raw`\sqcap`),s("Sqcup", "⊔", String.raw`\sqcup`),
    s("Wedge", "∧", String.raw`\wedge`),s("Vee", "∨", String.raw`\vee`),s("Big sum", "∑", String.raw`\sum_{|}`),
    s("Product", "∏", String.raw`\prod_{|}`),s("Coproduct", "∐", String.raw`\coprod_{|}`),
    s("Big cup", "⋃", String.raw`\bigcup_{|}`),s("Big cap", "⋂", String.raw`\bigcap_{|}`),
    s("Big oplus", "⨁", String.raw`\bigoplus_{|}`),s("Big otimes", "⨂", String.raw`\bigotimes_{|}`),
  ]},
  { name: "Relations", items: [
    s("Equal", "=", "="),s("Not equal", "≠", String.raw`\neq`),s("Approximately", "≈", String.raw`\approx`),
    s("Similar", "∼", String.raw`\sim`),s("Congruent", "≅", String.raw`\cong`),s("Equivalent", "≡", String.raw`\equiv`),
    s("Proportional", "∝", String.raw`\propto`),s("Less", "<", "<"),s("Greater", ">", ">"),
    s("Less or equal", "≤", String.raw`\leq`),s("Greater or equal", "≥", String.raw`\geq`),
    s("Much less", "≪", String.raw`\ll`),s("Much greater", "≫", String.raw`\gg`),
    s("Subset", "⊂", String.raw`\subset`),s("Subset equal", "⊆", String.raw`\subseteq`),
    s("Superset", "⊃", String.raw`\supset`),s("Superset equal", "⊇", String.raw`\supseteq`),
    s("Element of", "∈", String.raw`\in`),s("Not an element", "∉", String.raw`\notin`),
    s("Parallel", "∥", String.raw`\parallel`),s("Perpendicular", "⊥", String.raw`\perp`),
    s("Models", "⊨", String.raw`\models`),s("Precedes", "≺", String.raw`\prec`),
  ]},
  { name: "Calculus", items: [
    s("Integral", "∫", String.raw`\int |\,dx`),s("Definite integral", "∫ₐᵇ", String.raw`\int_{a}^{b} |\,dx`),
    s("Double integral", "∬", String.raw`\iint |\,dA`),s("Triple integral", "∭", String.raw`\iiint |\,dV`),
    s("Contour integral", "∮", String.raw`\oint |\,ds`),s("Differential", "d", String.raw`\mathrm{d}x`),
    s("Partial derivative", "∂f/∂x", String.raw`\frac{\partial |}{\partial x}`),
    s("Derivative", "df/dx", String.raw`\frac{d|}{dx}`),
    s("Second derivative", "d²/dx²", String.raw`\frac{d^2|}{dx^2}`),
    s("Limit", "lim", String.raw`\lim_{x\to |}`),s("Limit plus", "lim⁺", String.raw`\lim_{x\to 0^+} |`),
    s("Infinity", "∞", String.raw`\infty`),s("Nabla", "∇", String.raw`\nabla`),
    s("Gradient", "∇f", String.raw`\nabla |`),s("Laplacian", "∇²", String.raw`\nabla^2 |`),
    s("Summation", "∑", String.raw`\sum_{i=1}^{n} |`),s("Product", "∏", String.raw`\prod_{i=1}^{n} |`),
    s("Prime", "f′", "'"),s("Partial", "∂", String.raw`\partial`),
  ]},
  { name: "Functions", items: [
    s("Sine", "sin", String.raw`\sin`),s("Cosine", "cos", String.raw`\cos`),s("Tangent", "tan", String.raw`\tan`),
    s("Cosecant", "csc", String.raw`\csc`),s("Secant", "sec", String.raw`\sec`),s("Cotangent", "cot", String.raw`\cot`),
    s("Arcsine", "arcsin", String.raw`\arcsin`),s("Arccosine", "arccos", String.raw`\arccos`),s("Arctangent", "arctan", String.raw`\arctan`),
    s("Sinh", "sinh", String.raw`\sinh`),s("Cosh", "cosh", String.raw`\cosh`),s("Tanh", "tanh", String.raw`\tanh`),
    s("Natural log", "ln", String.raw`\ln`),s("Logarithm", "log", String.raw`\log`),s("Exponential", "exp", String.raw`\exp`),
    s("Log base", "log₂", String.raw`\log_{|}`),s("Max", "max", String.raw`\max`),s("Min", "min", String.raw`\min`),
    s("Supremum", "sup", String.raw`\sup`),s("Infimum", "inf", String.raw`\inf`),s("Determinant", "det", String.raw`\det`),
    s("Dimension", "dim", String.raw`\dim`),s("GCD", "gcd", String.raw`\gcd`),s("Kernel", "ker", String.raw`\ker`),
    s("Operator name", "f(x)", String.raw`\operatorname{|}`),
  ]},
  { name: "Sets & logic", items: [
    s("Real numbers", "ℝ", String.raw`\mathbb{R}`),s("Integers", "ℤ", String.raw`\mathbb{Z}`),
    s("Natural numbers", "ℕ", String.raw`\mathbb{N}`),s("Rational numbers", "ℚ", String.raw`\mathbb{Q}`),
    s("Complex numbers", "ℂ", String.raw`\mathbb{C}`),s("Empty set", "∅", String.raw`\emptyset`),
    s("In set", "∈", String.raw`\in`),s("Not in set", "∉", String.raw`\notin`),
    s("Intersection", "∩", String.raw`\cap`),s("Union", "∪", String.raw`\cup`),
    s("Set minus", "∖", String.raw`\setminus`),s("Subset equal", "⊆", String.raw`\subseteq`),
    s("For all", "∀", String.raw`\forall`),s("There exists", "∃", String.raw`\exists`),
    s("Does not exist", "∄", String.raw`\nexists`),s("Therefore", "∴", String.raw`\therefore`),
    s("Because", "∵", String.raw`\because`),s("Logical and", "∧", String.raw`\land`),
    s("Logical or", "∨", String.raw`\lor`),s("Not", "¬", String.raw`\neg`),
    s("Implies", "⇒", String.raw`\implies`),s("Iff", "⇔", String.raw`\iff`),
    s("Turnstile", "⊢", String.raw`\vdash`),s("Top", "⊤", String.raw`\top`),s("Bottom", "⊥", String.raw`\bot`),
  ]},
  { name: "Arrows", items: [
    s("Right", "→", String.raw`\rightarrow`),s("Left", "←", String.raw`\leftarrow`),
    s("Both", "↔", String.raw`\leftrightarrow`),s("Right double", "⇒", String.raw`\Rightarrow`),
    s("Left double", "⇐", String.raw`\Leftarrow`),s("Both double", "⇔", String.raw`\Leftrightarrow`),
    s("Long right", "⟶", String.raw`\longrightarrow`),s("Long left", "⟵", String.raw`\longleftarrow`),
    s("Mapsto", "↦", String.raw`\mapsto`),s("Long mapsto", "⟼", String.raw`\longmapsto`),
    s("Up", "↑", String.raw`\uparrow`),s("Down", "↓", String.raw`\downarrow`),
    s("Up double", "⇑", String.raw`\Uparrow`),s("Down double", "⇓", String.raw`\Downarrow`),
    s("Northeast", "↗", String.raw`\nearrow`),s("Southeast", "↘", String.raw`\searrow`),
    s("Hook right", "↪", String.raw`\hookrightarrow`),s("Harpoon right", "⇀", String.raw`\rightharpoonup`),
    s("To", "→", String.raw`\to`),s("Gets", "←", String.raw`\gets`),
  ]},
  { name: "Matrices", items: [
    s("Plain matrix", "▦", String.raw`\begin{matrix}| & b \\ c & d\end{matrix}`),
    s("Round matrix", "(▦)", String.raw`\begin{pmatrix}| & b \\ c & d\end{pmatrix}`),
    s("Square matrix", "[▦]", String.raw`\begin{bmatrix}| & b \\ c & d\end{bmatrix}`),
    s("Bar matrix", "|▦|", String.raw`\begin{vmatrix}| & b \\ c & d\end{vmatrix}`),
    s("Double bar matrix", "‖▦‖", String.raw`\begin{Vmatrix}| & b \\ c & d\end{Vmatrix}`),
    s("Small matrix", "₍▦₎", String.raw`\begin{smallmatrix}| & b \\ c & d\end{smallmatrix}`),
    s("Cases", "{▦", String.raw`\begin{cases}| & x>0 \\ 0 & x\leq 0\end{cases}`),
    s("Aligned equations", "=⋮", String.raw`\begin{aligned}| &= b \\ c &= d\end{aligned}`),
    s("Row separator", "↵", String.raw`\\ `, "matrix new line"),
    s("Column separator", "&", "&", "matrix next column"),
    s("Dots horizontal", "⋯", String.raw`\cdots`),s("Dots vertical", "⋮", String.raw`\vdots`),
    s("Dots diagonal", "⋱", String.raw`\ddots`),s("Identity matrix", "I₂", String.raw`\begin{pmatrix}1 & 0 \\ 0 & 1\end{pmatrix}`),
  ]},
  { name: "Brackets", items: [
    s("Parentheses", "( )", String.raw`\left(|\right)`),s("Square brackets", "[ ]", String.raw`\left[|\right]`),
    s("Curly braces", "{ }", String.raw`\left\{|\right\}`),s("Absolute value", "|x|", String.raw`\left\lvert |\right\rvert`),
    s("Norm", "‖x‖", String.raw`\left\lVert | \right\rVert`),s("Angle", "⟨ ⟩", String.raw`\left\langle |\right\rangle`),
    s("Floor", "⌊ ⌋", String.raw`\lfloor |\rfloor`),s("Ceiling", "⌈ ⌉", String.raw`\lceil |\rceil`),
    s("Small parentheses", "(x)", "(|)"),s("Middle bar", "|", String.raw`\mid`),
    s("Left brace", "{", String.raw`\{`),s("Right brace", "}", String.raw`\}`),
  ]},
  { name: "Accents", items: [
    s("Hat", "x̂", String.raw`\hat{|}`),s("Wide hat", "âb", String.raw`\widehat{|}`),
    s("Bar", "x̄", String.raw`\bar{|}`),s("Overline", "a̅b", String.raw`\overline{|}`),
    s("Underline", "a̲b", String.raw`\underline{|}`),s("Vector", "x⃗", String.raw`\vec{|}`),
    s("Over arrow", "⟶", String.raw`\overrightarrow{|}`),s("Left arrow", "⟵", String.raw`\overleftarrow{|}`),
    s("Tilde", "x̃", String.raw`\tilde{|}`),s("Wide tilde", "ãb", String.raw`\widetilde{|}`),
    s("Dot", "ẋ", String.raw`\dot{|}`),s("Double dot", "ẍ", String.raw`\ddot{|}`),
    s("Acute", "á", String.raw`\acute{|}`),s("Grave", "à", String.raw`\grave{|}`),
    s("Breve", "ă", String.raw`\breve{|}`),s("Check", "ǎ", String.raw`\check{|}`),
    s("Math ring", "å", String.raw`\mathring{|}`),
  ]},
  { name: "Symbols", items: [
    s("Infinity", "∞", String.raw`\infty`),s("Partial", "∂", String.raw`\partial`),s("Nabla", "∇", String.raw`\nabla`),
    s("Angle", "∠", String.raw`\angle`),s("Measured angle", "∡", String.raw`\measuredangle`),
    s("Degree", "°", String.raw`^\circ`),s("Ellipsis", "…", String.raw`\ldots`),
    s("Centered dots", "⋯", String.raw`\cdots`),s("Vertical dots", "⋮", String.raw`\vdots`),
    s("Aleph", "ℵ", String.raw`\aleph`),s("Hbar", "ℏ", String.raw`\hbar`),
    s("Ell", "ℓ", String.raw`\ell`),s("Re", "ℜ", String.raw`\Re`),s("Im", "ℑ", String.raw`\Im`),
    s("Prime", "′", String.raw`\prime`),s("Empty set", "∅", String.raw`\varnothing`),
    s("Diamond", "⋄", String.raw`\diamond`),s("Square", "□", String.raw`\square`),
    s("Triangle", "△", String.raw`\triangle`),s("Spadesuit", "♠", String.raw`\spadesuit`),
    s("Clubsuit", "♣", String.raw`\clubsuit`),s("Heartsuit", "♡", String.raw`\heartsuit`),
  ]},
  { name: "Type & space", items: [
    s("Text", "abc", String.raw`\text{|}`),s("Roman", "ABC", String.raw`\mathrm{|}`),
    s("Bold", "𝐱", String.raw`\mathbf{|}`),s("Italic", "𝑥", String.raw`\mathit{|}`),
    s("Blackboard", "𝔸", String.raw`\mathbb{|}`),s("Calligraphic", "𝒜", String.raw`\mathcal{|}`),
    s("Fraktur", "𝔄", String.raw`\mathfrak{|}`),s("Sans serif", "𝖺", String.raw`\mathsf{|}`),
    s("Typewriter", "𝚊", String.raw`\mathtt{|}`),s("Display style", "∑", String.raw`\displaystyle |`),
    s("Thin space", " ", String.raw`\,`),s("Medium space", " ", String.raw`\:`),
    s("Thick space", " ", String.raw`\;`),s("Quad", "□", String.raw`\quad`),
    s("Qquad", "□□", String.raw`\qquad`),s("Negative space", "↤", String.raw`\!`),
  ]},
  { name: "Examples", items: [
    s("Quadratic formula", "x = …", String.raw`x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}`),
    s("Euler’s identity", "eⁱπ+1", String.raw`e^{i\pi}+1=0`),
    s("Gaussian integral", "∫ e⁻ˣ²", String.raw`\int_{-\infty}^{\infty} e^{-x^2}\,dx=\sqrt{\pi}`),
    s("Pythagorean", "a²+b²", "a^2+b^2=c^2"),
    s("Binomial theorem", "(x+y)ⁿ", String.raw`(x+y)^n=\sum_{k=0}^{n}\binom{n}{k}x^{n-k}y^k`),
    s("Identity matrix", "I₂", String.raw`\begin{pmatrix}1 & 0 \\ 0 & 1\end{pmatrix}`),
  ]},
];
export const totalSymbols = symbolGroups.reduce((n, group) => n + group.items.length, 0);
